---
apiVersion: v1
kind: Secret
metadata:
  name: joshix2-joshix2-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/joshix2-backend-gitops
